module.exports = {
    "thankYou": "Thanks For Selecting Groot!",
    "supportServer": "Support Server",
    "inviteMe": "Invite Me",
    "vote": "Vote",
    "premium": "Premium",
    "premiumRequire": "Premium Require",
    "voteRequire": "Vote Require",
    "description": "Hey, It's **Groot** A Quality Music Bot With Breathtaking Features For Greater Experience While On Discord. **Groot** Is Making Music More Enhanced In Discord. Try **Groot** Now!",
    "devs": "Developer(s)",
    "contributors": "Contributor(s)",
    "websitedevs": "Website Developer(s)",
    "about": "About",
    "thanks": "Thanks For Selecting Groot",
    "blacklistedGuild": "Oops! Looks Like This Server Has Been BlackListed By Our Developer's/Admin's! Contact Our [Support Server]({{supportUrl}}) For More Information!\nThank You **Team Groot!**",
    "blacklist": "BlackListed! You Can't Use Groot Here",
    "premiumGuild": "You Need To Upgrade This Server To Use **[Premium]({{premiumUrl}})** Commands Here!\n**[Click here]({{premiumUrl}})** Or Press **Premium** Button!",
    "premiumUser": "You Need To Upgrade Into **[Premium]({{premiumUrl}})** Commands Here!\n**[Click here]({{premiumUrl}})** Or Press **Premium** Button!",
    "voter": "You Must **[Vote](https://grootbot.pro/vote)** Me To Use Votable Commands.\nIf You Want To Disable This **[Click Here]({{premiumUrl}})** To Purchase **[Premium]({{premiumUrl}})** And Enjoy Non-Stop Music.",
    "mustperm": "You Must Have The `{{permArry}}` Permission To Use This Command!",
    "iDontHavePerm": "I Don't Have Permission To `{{permArry}}` Missing Permissions!",
    "afk": "{{user}}, User Is Now AFK For Reason - **{{afkReason}}**",
    "afkRemove": "AFK Has Been Removed!",
    "quality": "The Best Quality Music Bot!",
    "guildOwner": "This Command Can Only Be Used By Owner Of This Server!",
    "upperRole": "You Need To Have Upper Role Then Me To Use This Command!",
    "checkPerm": "I Don't Have Enough Permission To Run This Command!\n> Click On The Button Below To Fix The Problem",
    "playing": "I'm Already Playing Music In Channel `{{vc}}`",
    "nowPlaying": "Now Playing",
    "requester": "Requester",
    "duration": "Duration",
    "botVolume": "The Bot's Volume Is Currently Above 100%. You May Experience Distortion.",
    "queueEnded": "Queue Ended",
    "addMoreSong": "Add More Songs And Continue The Party On\n\n**[Support Server]({{supportUrl}})**",
    "247": "I've Left The Voice Channel, Enable 24/7 Function To Keep Me In Voice Channel",
    "moreInGroot": "More In Groot",
    "website": "**[Website]({{websiteUrl}})**",
    "leftVc": "Groot Has Left The Voice Channel As I'm Not Playing Any Songs!",
    "skipped": "Skipped To The Next Track.",
    "addedToQueue": "Added To Queue",
    "tracks": "Tracks From",
    "prepairing": "preparing To Play",
    "selectTrack": "Select Tracks You Want To Add To The Queue.",
    "makeASelection": "Make A Selection",
    "cancelSelection": "Cancelled The Selection",
    "playingQueue": "Playing {{title}} And Queued {{selectedValue}} Track {{trackValues}}",
    "trackQueue": "Track Queued - Position #{{position}}",
    "noSongInQueue": "No Songs Are Currently In Queue",
    "cooldown": "This Command Is On Cooldown For `{{rateLimits}}`",
    "filterClear": "Successfully Cleared The Filters",
    "poweredBy": "Powered By {{service}}",
}
