module.exports = {
    "errors": {
        "mustHaveSong": "You Must Have To Play A Song To Use This Command!",
        "noQueue": "You Don't Have Any Song's In Queue!",
        "noPlaylist": "You Have No Playlist Available!"
    },
    "common": { 
        "selection": "Make A Selection",
        "cancelSelection": "Cancelled The Selection",
        "playlistName": "Please Enter A Playlist Name!",
        "playlistInfo": "Playlist Info",
        "outof": "Out Of",
        "noTrack": "There Is No Track In This Playlist!",
        "noDups": "There Is No Duplicate Song's In Your PLaylist!",
        "shouldbeNum": "It Should Be An Number!",
        "noInput": "No Input Recived!",
        "args": "You Need To Select An Options Form Below",
        "playlistNameExceeded": "Sorry, You Have Exceeded The Playlist Name Limit!",
        "playlistNameInvalid": "Sorry, You Have Entered An Invalid Playlist Name! It Must Not Be A URL!",
    },
    "addCurrentSelect": "Select The Playlist You Want To Add The Current Track",
    "addCurrentSuccessfull": "Successfully Added To The Playlist With Name **{{song}}**",
    "addQueueSelect": "Select The Playlist You Want To Add The Current Queue",
    "addQueueSuccessfull": "Successfully Added Queue To The Playlist With Name **{{song}}**",
    "createAlready": "Already An Playlist Is Created With Name **{{playlist}}**!",
    "createExceeded": "Sorry, You Have Exceeded The Playlist Making Limit!",
    "createSuccessfull": "Successfully Created Personal Playlist With Name **{{playlist}}**",
    "deleteSelect": "Select The Playlist You Want To Delete",
    "deleteSuccessfull": "Successfully Deleted Personal Playlist With Name **{{playlist}}**",
    "listSelect": "Select The Playlist You Want To Get Info",
    "playSelect": "Select The Playlist You Want To Load",
    "startedPlaying": "Started Playing `{{tracks}}` Track(s) From The Playlist **{{playlist}}**",
    "removeDupsSelect": "Select The Playlist You Want To Remove Duplicate",
    "removeDupsSuccessfull": "Successfully Removed `{{tracks}}` Duplicate Songs",
    "removeTrackSelect": "Select The Playlist You Want To Add The Current Track",
    "removeTrackNum": "Now Specify The Track Number.\n**If You Don't Know Check Playlist Info!**",
    "removeTrackIndex": "There Is No Track With The Index `{{index}}`",
    "removeTrackSuccessfull": "Successfully Removed The Song!\n__**Song Name -**__\n[{{trackTitle}}]({{trackUrl}})"
}