module.exports = {
  "247": "Ich habe den Sprachkanal verlassen und rund um die Uhr aktiviert, um mich im Sprachkanal zu halten",
  "thankYou": "Danke, dass du Groot ausgewählt hast!",
  "supportServer": "Support Server",
  "inviteMe": "Lade mich ein",
  "vote": "Abstimmung",
  "premium": "Prämie",
  "premiumRequire": "Prämie erfordern",
  "voteRequire": "Abstimmung erfordern",
  "description": "Hey, es ist ** Groot ** ein qualitativ hochwertiger Musikbot mit atemberaubenden Funktionen für mehr Erfahrung während der Zwietracht.** Groot ** macht die Musik in Zwietracht stärker.Versuche ** Groot ** jetzt!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Website -Entwickler (en)",
  "about": "Um",
  "thanks": "Danke für die Auswahl von Groot",
  "blacklistedGuild": "Hoppla!Sieht so aus, als wurde dieser Server von den unserem Entwickler/Administrator auf die schwarze Liste gesetzt!Wenden Sie sich an unseren [{{websiteUrl}}]**",
  "leftVc": "Groot hat den Sprachkanal verlassen, da ich keine Songs spiele!",
  "skipped": "Übersprungen zum nächsten Track.",
  "addedToQueue": "Hinzufügen zur Warteschlange",
  "tracks": "Tracks von",
  "prepairing": "Vorbereitung auf das Spielen",
  "selectTrack": "Wählen Sie Tracks aus, die Sie zur Warteschlange hinzufügen möchten.",
  "makeASelection": "Eine Auswahl treffen",
  "cancelSelection": "Stornierte die Auswahl",
  "playingQueue": "Spielen {{title}} und in der Warteschlange {{selectedValue}} Track {{trackValues}}",
  "trackQueue": "Track -Warteschlange - Position #{{position}}",
  "noSongInQueue": "Derzeit sind keine Songs in der Warteschlange",
  "cooldown": "Dieser Befehl ist auf der Abklingzeit für `{{ratelimits}}`",
  "filterClear": "Erfolgreich die Filter löscht",
  "poweredBy": "Angetrieben von {{service}}"
}