module.exports = {
  "247": "Ich habe den Sprachkanal verlassen und rund um die Uhr aktiviert, um mich im Sprachkanal zu halten",
  "thankYou": "Vielen Dank für die Auswahl von Groot!",
  "supportServer": "Support Server",
  "inviteMe": "Lade mich ein",
  "vote": "Abstimmung",
  "premium": "Prämie",
  "premiumRequire": "Premium -Erfordernis",
  "voteRequire": "Abstimmung erforderlich",
  "description": "Hey, es ist ** Groot ** ein hochwertiger Musikbot mit atemberaubenden Funktionen für mehr Erfahrung während der Zwietracht. ** Groot ** macht die Musik in Zwietracht stärker. Versuchen Sie es jetzt ** Groot ** jetzt!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Website -Entwickler (en)",
  "about": "Um",
  "thanks": "Danke für die Auswahl von Groot",
  "blacklistedGuild": "Hoppla! Sieht so aus, als wurde dieser Server von den unserem Entwickler/Administrator auf die schwarze Liste gesetzt! Wenden Sie sich an unseren [Support Server]({{supportUrl}}), um weitere Informationen zu erhalten!\nDanke ** Team Groot! **",
  "blacklist": "Blacklist! Sie können Groot hier nicht verwenden",
  "premiumGuild": "Sie müssen diesen Server auf die Verwendung von ** [Premium]({{premiumUrl}}) ** hier aktualisieren!\n** [Klicken Sie hier]({{premiumUrl}}) ** oder drücken Sie ** Premium ** Taste!",
  "premiumUser": "Sie müssen in ** [Premium]({{premiumUrl}}) ** Befehle hier ein Upgrade!\n** [Klicken Sie hier]({{premiumUrl}}) ** oder drücken Sie ** Premium ** Taste!",
  "voter": "Sie müssen ** [Abstimmung](https://grootbot.pro/vote) ** Ich, um stimmbare Befehle zu verwenden.\nWenn Sie dies deaktivieren möchten ** [hier klicken]({{premiumUrl}}) ** zum Kauf ** [Premium]({{premiumUrl}}) ** und genießen Sie Nonstop-Musik.",
  "mustperm": "Sie müssen die Erlaubnis von `{{permArry}}` haben, diesen Befehl zu verwenden!",
  "iDontHavePerm": "Ich habe nicht die Erlaubnis, zu `{{permArry}}` fehlende Berechtigungen!",
  "afk": "00undefined00, der Benutzer ist jetzt AFK aus Gründen - ** {{afkReason}} **",
  "afkRemove": "AFK wurde entfernt!",
  "quality": "Der qualitativ hochwertige Musikbot!",
  "guildOwner": "Dieser Befehl kann nur vom Eigentümer dieses Servers verwendet werden!",
  "upperRole": "Sie müssen die obere Rolle spielen und dann diesen Befehl verwenden!",
  "checkPerm": "Ich habe nicht genug Erlaubnis, diesen Befehl auszuführen!\n> Klicken Sie auf die Schaltfläche unten, um das Problem zu beheben",
  "playing": "Ich spiele bereits Musik in Channel `{{vc}}`",
  "nowPlaying": "Läuft gerade",
  "requester": "Anforderer",
  "duration": "Dauer",
  "botVolume": "Das Volumen des Bots liegt derzeit über 100%. Sie können Verzerrungen erleben.",
  "queueEnded": "Warteschlange endete",
  "addMoreSong": "Fügen Sie weitere Songs hinzu und setzen Sie die Party fort\n\n** [Support Server]({{supportUrl}}) **",
  "moreInGroot": "Mehr in Groot",
  "website": "**[Website]({{websiteUrl}})**",
  "leftVc": "Groot hat den Sprachkanal verlassen, da ich keine Songs spiele!",
  "skipped": "Übersprungen zum nächsten Track.",
  "addedToQueue": "Hinzufügen zur Warteschlange",
  "tracks": "Tracks von",
  "prepairing": "Vorbereitung zum Spielen",
  "selectTrack": "Wählen Sie Tracks aus, die Sie zur Warteschlange hinzufügen möchten.",
  "makeASelection": "Eine Auswahl treffen",
  "cancelSelection": "Stornierte die Auswahl",
  "playingQueue": "Spielen {{title}} und in der Warteschlange {{selectedValue}} Track {{trackValues}}",
  "trackQueue": "Track -Warteschlange - Position #{{position}}",
  "noSongInQueue": "Derzeit sind keine Songs in der Warteschlange",
  "cooldown": "Dieser Befehl hat eine Abklingzeit von `{{rateLimits}}`",
  "filterClear": "Filter erfolgreich gelöscht"
}