module.exports = {
  "247": "Ho lasciato il canale vocale, abilita la funzione 24/7 per tenermi nel canale vocale",
  "thankYou": "Grazie per aver selezionato Groot!",
  "supportServer": "Server di supporto",
  "inviteMe": "Invitami",
  "vote": "Votazione",
  "premium": "Premium",
  "premiumRequire": "Premium Requisito",
  "voteRequire": "Voto richiedere",
  "description": "Ehi, è ** Groot ** un bot di musica di qualità con caratteristiche mozzafiato per una maggiore esperienza durante la discordia. ** Groot ** sta rendendo la musica più migliorata in discordia. Prova ** groot ** ora!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Sviluppatori di siti Web",
  "about": "Di",
  "thanks": "Grazie per aver selezionato Groot",
  "blacklistedGuild": "Oops! Sembra che questo server sia stato inserito nella lista nera dal nostro sviluppatore/amministratore! Contatta il nostro [Support Server]({{supportUrl}}) per ulteriori informazioni!\nGrazie ** Team Groot! **",
  "blacklist": "Liste in friglia! Non puoi usare Groot qui",
  "premiumGuild": "È necessario aggiornare questo server per utilizzare i comandi ** [Premium]({{premiumUrl}}) ** qui!\n** [Clicca qui]({{premiumUrl}}) ** o premere ** Pulsante premium **!",
  "premiumUser": "Devi aggiornare i comandi ** [Premium]({{premiumUrl}}) ** qui!\n** [Clicca qui]({{premiumUrl}}) ** o premere ** Pulsante Premium **!",
  "voter": "Devi ** [voto](https://grootbot.pro/vote) ** per usare i comandi votabili.\nSe vuoi disabilitare questo ** [clicca qui]({{premiumUrl}}) ** per acquistare ** [Premium]({{premiumUrl}}) ** e goditi la musica senza sosta.",
  "mustperm": "Devi avere l'autorizzazione `{{permArry}}` per usare questo comando!",
  "iDontHavePerm": "Non ho il permesso di `$ {Permarry}` Permessi mancanti!",
  "afk": "00Andefined00, l'utente è ora AFK per motivo - ** {{afkReason}} **",
  "afkRemove": "AFK è stato rimosso!",
  "quality": "Il bot di musica migliore di qualità!",
  "guildOwner": "Questo comando può essere utilizzato solo dal proprietario di questo server!",
  "upperRole": "Devi avere un ruolo superiore quindi per usare questo comando!",
  "checkPerm": "Non ho abbastanza permesso per eseguire questo comando!\n> Fare clic sul pulsante in basso per risolvere il problema",
  "playing": "Sto già suonando musica in Channel `{{vc}}`",
  "nowPlaying": "Ora giocando",
  "requester": "Richiedente",
  "duration": "Durata",
  "botVolume": "Il volume del bot è attualmente superiore al 100%. Potresti provare distorsioni.",
  "queueEnded": "La coda è finita",
  "addMoreSong": "Aggiungi più canzoni e continua la festa su\n\n** [Support Server]({{supportUrl}}) **",
  "moreInGroot": "Più a Groot",
  "website": "**[Website]({{websiteUrl}})**",
  "leftVc": "Groot ha lasciato il canale vocale perché non sto suonando canzoni!",
  "skipped": "Saltato alla traccia successiva.",
  "addedToQueue": "Aggiunto alla coda",
  "tracks": "Tracce da",
  "prepairing": "Prepararsi per giocare",
  "selectTrack": "Seleziona le tracce che si desidera aggiungere alla coda.",
  "makeASelection": "Fare una selezione",
  "cancelSelection": "Annullato la selezione",
  "playingQueue": "Giocando {{title}} e coda {{selectedValue}} Traccia {{trackValues}}",
  "trackQueue": "Traccia in coda - Posizione #{{position}}",
  "noSongInQueue": "Nessuna canzone è attualmente in coda",
  "cooldown": "Questo comando è al tempo di recupero per `00UNDEFINED00`",
  "filterClear": "Ha cancellato con successo i filtri"
}