module.exports = {
  "247": "Ho lasciato il canale vocale, abilita la funzione 24/7 per tenermi nel canale vocale",
  "thankYou": "Grazie per aver selezionato Groot!",
  "supportServer": "Server di supporto",
  "inviteMe": "Invitami",
  "vote": "Votazione",
  "premium": "Premium",
  "premiumRequire": "Premium Requisito",
  "voteRequire": "Voto richiedere",
  "description": "Ehi, è ** Groot ** un bot di musica di qualità con caratteristiche mozzafiato per una maggiore esperienza durante la discordia.** Groot ** sta rendendo la musica più migliorata in discordia.Prova ** groot ** ora!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Sviluppatori di siti Web",
  "about": "Di",
  "thanks": "Grazie per aver selezionato Groot",
  "blacklistedGuild": "Oops!Sembra che questo server sia stato inserito nella lista nera dal nostro sviluppatore/amministratore!Contatta il nostro [{{websiteUrl}}]**",
  "leftVc": "Groot ha lasciato il canale vocale perché non sto suonando canzoni!",
  "skipped": "Saltato alla traccia successiva.",
  "addedToQueue": "Aggiunto alla coda",
  "tracks": "Tracce da",
  "prepairing": "prepararsi a giocare",
  "selectTrack": "Seleziona le tracce che si desidera aggiungere alla coda.",
  "makeASelection": "Fare una selezione",
  "cancelSelection": "Annullato la selezione",
  "playingQueue": "Giocando {{title}} e coda {{selectedValue}} Traccia {{trackValues}}",
  "trackQueue": "Traccia in coda - Posizione #{{position}}",
  "noSongInQueue": "Nessuna canzone è attualmente in coda",
  "cooldown": "Questo comando è su cooldown per `{{ratelimits}`",
  "filterClear": "Ha cancellato con successo i filtri",
  "poweredBy": "Alimentato da {{service}}"
}