module.exports = {
  "247": "Dejé el canal de voz, habilita la función 24/7 para mantenerme en el canal de voz",
  "thankYou": "¡Gracias por seleccionar Groot!",
  "supportServer": "Servidor de soporte",
  "inviteMe": "Invitame",
  "vote": "Votar",
  "premium": "De primera calidad",
  "premiumRequire": "Premium requiere",
  "voteRequire": "El voto requiere",
  "description": "Oye, es ** Groot ** un bot de música de calidad con características impresionantes para una mayor experiencia mientras está en Discord. ** Groot ** está haciendo que la música sea más mejorada en Discord. Prueba ** Groot ** ahora!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Desarrolladores del sitio web",
  "about": "Sobre",
  "thanks": "Gracias por seleccionar Groot",
  "blacklistedGuild": "¡Ups! ¡Parece que este servidor ha sido en la lista negra por nuestro desarrollador/administrador! ¡Póngase en contacto con nuestro [servidor de soporte]({{supportUrl}}) para obtener más información!\n¡Gracias ** Team Groot! **",
  "blacklist": "¡Lista negra! No puedes usar Groot aquí",
  "premiumGuild": "¡Debe actualizar este servidor para usar ** [Premium]({{premiumUrl}}) ** Comandos aquí!\n** [Haga clic aquí]({{premiumUrl}}) ** o presione ** Premium ** Botón!",
  "premiumUser": "¡Debe actualizar a ** [Premium]({{premiumUrl}}) ** Comandos aquí!\n** [Haga clic aquí]({{premiumUrl}}) ** o presione ** Premium ** Botón!",
  "voter": "Debe ** [votar](https://top.gg/bot/853583833747161091/vote) ** Me para usar comandos votables.\nSi desea deshabilitar esto ** [Haga clic aquí]({{premiumUrl}}) ** para comprar ** [Premium]({{premiumUrl}}) ** y disfrutar de música sin parar.",
  "mustperm": "¡Debe tener el permiso `{{permArry}}` para usar este comando!",
  "iDontHavePerm": "No tengo permiso para `{{permArry}}` ¡Permisos faltantes!",
  "afk": "00undefined00, el usuario ahora es AFK por la razón - ** {{afkReason}} **",
  "afkRemove": "¡AFK ha sido eliminado!",
  "quality": "¡El bot de música de mejor calidad!",
  "guildOwner": "¡Este comando solo puede ser utilizado por el propietario de este servidor!",
  "upperRole": "¡Necesitas tener un rol superior que yo para usar este comando!",
  "checkPerm": "¡No tengo suficiente permiso para ejecutar este comando!\n> Haga clic en el botón de abajo para solucionar el problema",
  "playing": "Ya estoy tocando música en canal `{{vc}}`",
  "nowPlaying": "Jugando ahora",
  "requester": "Solicitante",
  "duration": "Duración",
  "botVolume": "El volumen del bot está actualmente por encima del 100%. Puede experimentar distorsión.",
  "queueEnded": "La cola terminó",
  "addMoreSong": "Agrega más canciones y continúa la fiesta en\n\n** [Servidor de soporte]({{supportUrl}}) **",
  "moreInGroot": "Más en Groot",
  "website": "**[Website]({{websiteUrl}})**",
  "leftVc": "¡Groot ha dejado el canal de voz ya que no estoy tocando ninguna canción!",
  "skipped": "Saltó a la siguiente pista.",
  "addedToQueue": "Agregado a la cola",
  "tracks": "Pistas de",
  "prepairing": "Preparando para jugar",
  "selectTrack": "Seleccione pistas que desea agregar a la cola.",
  "makeASelection": "Has una elección",
  "cancelSelection": "Canceló la selección",
  "playingQueue": "Reproduciendo {{title}} y en cola {{selectedValue}} pistas {{trackValues}}",
  "trackQueue": "Pista en cola - Posición #{{position}}",
  "noSongInQueue": "No hay canciones actualmente en cola",
  "cooldown": "Este comando está en el tiempo de reutilización para `00undefined00`",
  "filterClear": "Limpió con éxito los filtros"
}