module.exports = {
  "247": "Dejé el canal de voz, habilita la función 24/7 para mantenerme en el canal de voz",
  "thankYou": "¡Gracias por seleccionar Groot!",
  "supportServer": "Servidor de soporte",
  "inviteMe": "Invitame",
  "vote": "Votar",
  "premium": "De primera calidad",
  "premiumRequire": "Premium requerir",
  "voteRequire": "El voto requiere",
  "description": "Oye, es ** Groot ** un bot de música de calidad con características impresionantes para una mayor experiencia mientras está en Discord.** Groot ** está haciendo que la música sea más mejorada en Discord.Prueba ** Groot ** ahora!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Desarrolladores del sitio web",
  "about": "Acerca de",
  "thanks": "Gracias por seleccionar Groot",
  "blacklistedGuild": "¡Ups!¡Parece que este servidor ha sido en la lista negra por nuestro desarrollador/administrador!¡Póngase en contacto con nuestro [{{websiteUrl}}]**",
  "leftVc": "¡Groot ha dejado el canal de voz ya que no estoy tocando ninguna canción!",
  "skipped": "Dije a la siguiente pista.",
  "addedToQueue": "Agregado a la cola",
  "tracks": "Pistas de",
  "prepairing": "Preparándose para jugar",
  "selectTrack": "Seleccione pistas que desea agregar a la cola.",
  "makeASelection": "Has una elección",
  "cancelSelection": "Canceló la selección",
  "playingQueue": "Reproduciendo {{title}} y en cola {{selectedValue}} Pista {{trackValues}}",
  "trackQueue": "Track Queed - Posición #{{position}}",
  "noSongInQueue": "No hay canciones actualmente en cola",
  "cooldown": "Este comando está en el tiempo de reutilización para `{{ratElimits}}`",
  "filterClear": "Limpió con éxito los filtros",
  "poweredBy": "Alimentado por {{service}}"
}