module.exports = {
  "247": "Eu deixei o canal de voz, ative a função 24/7 para me manter em canal de voz",
  "thankYou": "Obrigado por selecionar Groot!",
  "supportServer": "Servidor de suporte",
  "inviteMe": "Me convide",
  "vote": "Voto",
  "premium": "Prêmio",
  "premiumRequire": "Premium requer",
  "voteRequire": "Voto exige",
  "description": "Ei, é ** Groot ** um bot de qualidade com recursos de tirar o fôlego para maior experiência enquanto estiver na discórdia. ** Groot ** está tornando a música mais aprimorada na discórdia. Experimente ** Groot ** agora!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Desenvolvedor (s) de sites",
  "about": "Sobre",
  "thanks": "Obrigado por selecionar Groot",
  "blacklistedGuild": "Opa! Parece que este servidor foi na lista negra de nossos desenvolvedores/administradores! Entre em contato com o nosso [Servidor de Suporte]({{supportUrl}}) para obter mais informações!\nObrigado ** Team Groot! **",
  "blacklist": "Lista negra! Você não pode usar Groot aqui",
  "premiumGuild": "Você precisa atualizar este servidor para usar ** [Premium]({{premiumUrl}}) ** Comandos aqui!\n** [Clique aqui]({{premiumUrl}}) ** ou pressione ** Botão Premium **!",
  "premiumUser": "Você precisa atualizar para ** [Premium]({{premiumUrl}}) ** Comandos aqui!\n** [Clique aqui]({{premiumUrl}}) ** ou pressione ** Botão Premium **!",
  "voter": "Você deve ** [votar](https://grootbot.pro/vote) ** me para usar comandos votáveis.\nSe você deseja desativar isso ** [Clique aqui]({{premiumUrl}}) ** para comprar ** [Premium]({{premiumUrl}}) ** e desfrute de música sem parar.",
  "mustperm": "Você deve ter a permissão `{{permArry}}` para usar este comando!",
  "iDontHavePerm": "Não tenho permissão para `{{permArry}}` Permissões ausentes!",
  "afk": "00undefined00, o usuário agora está AFK para a razão - ** {{afkReason}} **",
  "afkRemove": "AFK foi removido!",
  "quality": "O BOT Music Bot de melhor qualidade!",
  "guildOwner": "Este comando só pode ser usado pelo proprietário deste servidor!",
  "upperRole": "Você precisa ter um papel superior e depois eu usar este comando!",
  "checkPerm": "Não tenho permissão suficiente para executar este comando!\n> Clique no botão abaixo para corrigir o problema",
  "playing": "Já estou tocando música no canal `{{vc}}`",
  "nowPlaying": "Agora jogando",
  "requester": "Solicitante",
  "duration": "Duração",
  "botVolume": "O volume do bot está atualmente acima de 100%. Você pode experimentar distorção.",
  "queueEnded": "Fila terminou",
  "addMoreSong": "Adicione mais músicas e continue a festa em\n\n** [Servidor de suporte]({{supportUrl}}) **",
  "moreInGroot": "Mais em Groot",
  "website": "**[Website]({{websiteUrl}})**",
  "leftVc": "Groot deixou o canal de voz porque não estou tocando nenhuma música!",
  "skipped": "Pulou para a próxima faixa.",
  "addedToQueue": "Adicionado à fila",
  "tracks": "Faixas de",
  "prepairing": "Preparando para jogar",
  "selectTrack": "Selecione faixas que deseja adicionar à fila.",
  "makeASelection": "Faça uma seleção",
  "cancelSelection": "Cancelou a seleção",
  "playingQueue": "Jogando {{title}} e fila {{selectedValue}} faixa {{trackValues}}",
  "trackQueue": "Faixa de faixa - Posição #{{position}}",
  "noSongInQueue": "Nenhuma música está atualmente na fila",
  "cooldown": "Este comando está em recarga para `00undefined00`",
  "filterClear": "Limpou com sucesso os filtros"
}