module.exports = {
  "247": "Eu deixei o canal de voz, ative a função 24/7 para me manter em canal de voz",
  "thankYou": "Obrigado por selecionar Groot!",
  "supportServer": "Servidor de suporte",
  "inviteMe": "Me convide",
  "vote": "Voto",
  "premium": "Prêmio",
  "premiumRequire": "Premium requer",
  "voteRequire": "Votação exige",
  "description": "Ei, é ** Groot ** Um bot de qualidade com recursos de tirar o fôlego para maior experiência enquanto estiver na discórdia.** Groot ** está tornando a música mais aprimorada na discórdia.Experimente ** Groot ** agora!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Desenvolvedor (s) de sites",
  "about": "Sobre",
  "thanks": "Obrigado por selecionar Groot",
  "blacklistedGuild": "Opa!Parece que este servidor foi na lista negra de nossos desenvolvedores/administradores!Entre em contato com o nosso [{{websiteUrl}}]**",
  "leftVc": "Groot deixou o canal de voz porque não estou tocando nenhuma música!",
  "skipped": "Pulou para a próxima faixa.",
  "addedToQueue": "Adicionado à fila",
  "tracks": "Faixas de",
  "prepairing": "preparando -se para jogar",
  "selectTrack": "Selecione faixas que você deseja adicionar à fila.",
  "makeASelection": "Faça uma seleção",
  "cancelSelection": "Cancelou a seleção",
  "playingQueue": "Jogando {{title}} e fila {{selectedValue}} faixa {{trackValues}}",
  "trackQueue": "Faixa de faixa - Posição #{{position}}",
  "noSongInQueue": "Nenhuma música está atualmente na fila",
  "cooldown": "Este comando está em recarga para `{{ratelimits}}`",
  "filterClear": "Limpou com sucesso os filtros",
  "poweredBy": "Alimentado por {{service}}"
}