module.exports = {
  '247': "J'ai laissé le canal vocal, activez la fonction 24/7 pour me garder dans le canal vocal",
  thankYou: "Merci d'avoir sélectionné Groot!",
  supportServer: "Serveur d'assistance",
  inviteMe: 'Invite moi',
  vote: 'Voter',
  premium: 'Prime',
  premiumRequire: 'Premium exige',
  voteRequire: 'Le vote exige',
  description: "Hé, c'est ** Groot ** un bot musical de qualité avec des fonctionnalités à couper le souffle pour une plus grande expérience lors de la discorde. ** Groot ** rend la musique plus améliorée dans Discord. Essayez ** Groot ** maintenant!",
  devs: 'Developer(s)',
  contributors: 'Contributor(s)',
  websitedevs: 'Développeur (s) de site Web (s)',
  about: 'À propos de',
  thanks: "Merci d'avoir sélectionné Groot",
  blacklistedGuild: "Oops! On dirait que ce serveur a été mis sur liste noire par notre développeur / Admin! Contactez notre [Support Server]({{supportUrl}}) pour plus d'informations!\n" +
    'Merci ** Team Groot! **',
  blacklist: 'Sur liste noire! Vous ne pouvez pas utiliser Groot ici',
  premiumGuild: 'Vous devez mettre à niveau ce serveur pour utiliser ** [Premium]({{premiumUrl}}) ** Commandes ici!\n' +
    '** [Cliquez ici]({{PremiumUrl}}) ** ou appuyez sur ** Bouton Premium **!',
  premiumUser: 'Vous devez passer en ** [Premium]({{premiumUrl}}) ** Commandes ici!\n' +
    '** [Cliquez ici]({{PremiumUrl}}) ** ou appuyez sur ** Bouton Premium **!',
  voter: 'Vous devez ** [vote](https://top.gg/bot/853583833747161091/vote) ** moi pour utiliser des commandes votables.\n' +
    'Si vous souhaitez désactiver ce ** [cliquez ici]({{premiumUrl}}) ** pour acheter ** [Premium]({{premiumUrl}}) ** et profiter de la musique non-stop.',
  mustperm: "Vous devez avoir le `{{permArry}}` Permission d'utiliser cette commande!",
  iDontHavePerm: "Je n'ai pas l'autorisation de `{{permArry}}` Autorisations manquantes!",
  afk: "{{user}}, l'utilisateur est maintenant afk pour la raison - ** {{afkReason}} **",
  afkRemove: "L'AFK a été supprimé!",
  quality: 'Le meilleur bot musical de qualité! <:musicsettings:894622659025985536>',
  guildOwner: 'Cette commande ne peut être utilisée que par le propriétaire de ce serveur!',
  upperRole: 'Vous devez avoir un rôle supérieur puis moi pour utiliser cette commande!',
  checkPerm: "Je n'ai pas assez de permission pour exécuter cette commande!\n" +
    '> Cliquez sur le bouton ci-dessous pour résoudre le problème',
  playing: 'Je joue déjà de la musique dans Channel `{{vc}}`',
  nowPlaying: 'Lecture en cours',
  requester: 'Demandeur',
  duration: 'Durée',
  botVolume: 'Le volume du bot est actuellement supérieur à 100%. Vous pouvez ressentir une distorsion.',
  queueEnded: "La file d'attente s'est terminée",
  addMoreSong: 'Ajoutez plus de chansons et continuez la fête sur\n' +
    '\n' +
    '**[Support Server]({{supportUrl}})**',
  moreInGroot: 'Plus à Groot',
  website: '**[Website]({{websiteUrl}})**',
  leftVc: 'Groot a quitté la chaîne vocale car je ne joue aucune chanson!',
  skipped: 'Sauté sur la piste suivante.',
  addedToQueue: "Ajouté à la file d'attente",
  tracks: 'Des pistes de',
  prepairing: 'Prépaire pour jouer',
  selectTrack: "Sélectionnez des pistes que vous souhaitez ajouter à la file d'attente.",
  makeASelection: 'Faire un choix',
  cancelSelection: 'Annulé la sélection',
  playingQueue: "Playing {{title}} et en file d'attente {{selectedValue}} track {{trackValues}}",
  trackQueue: 'Track Queued - Position #{{position}}',
  noSongInQueue: "Aucune chanson n'est actuellement en file d'attente",
  "cooldown": "Cette commande est en recharge pendant `{{rateLimits}}`",
  "filterClear": "Effacer les filtres avec succès"
}