module.exports = {
  "247": "J'ai laissé le canal vocal, activez une fonction 24/7 pour me garder dans le canal vocal",
  "thankYou": "Merci d'avoir sélectionné Groot!",
  "supportServer": "Serveur d'assistance",
  "inviteMe": "Invite moi",
  "vote": "Vote",
  "premium": "Prime",
  "premiumRequire": "Premium Besoin",
  "voteRequire": "Le vote exige",
  "description": "Hé, c'est ** Groot ** un bot musical de qualité avec des fonctionnalités à couper le souffle pour une plus grande expérience lors de la discorde.** Groot ** rend la musique plus améliorée en discorde.Essayez ** Groot ** maintenant!",
  "devs": "Developer(s)",
  "contributors": "Contributor(s)",
  "websitedevs": "Développeur (s) de site Web (s)",
  "about": "À propos",
  "thanks": "Merci d'avoir sélectionné Groot",
  "blacklistedGuild": "Oops!On dirait que ce serveur a été mis sur liste noire par nos développeurs / Admin!Contactez notre [{{websiteUrl}}]**",
  "leftVc": "Groot a quitté la chaîne vocale car je ne joue aucune chanson!",
  "skipped": "Sauté à la piste suivante.",
  "addedToQueue": "Ajouté à la file d'attente",
  "tracks": "Traces de",
  "prepairing": "se préparer à jouer",
  "selectTrack": "Sélectionnez des pistes que vous souhaitez ajouter à la file d'attente.",
  "makeASelection": "Choisissez",
  "cancelSelection": "Annulé la sélection",
  "playingQueue": "Jouer {{title}} et en file d'attente {{selectedValue}} Piste {{trackValues}}",
  "trackQueue": "Track Queued - Position # {{position}}",
  "noSongInQueue": "Aucune chanson n'est actuellement en file d'attente",
  "cooldown": "Cette commande est en recharge pour `{{Ratelimits}}`",
  "filterClear": "Effacer avec succès les filtres",
  "poweredBy": "Propulsé par {{service}}"
}